# .yml inventory file for DHCP setup
# originally written for vyos-blue-dhcp.yml playbook
vyos:
  hosts:
    10.0.17.200:
      hostname: bluex-fw
      lan_ip: 10.0.5.2
      lan_net: 10.0.5.0/24
      dhcp: 10.0.17.4
      shared_network: BLUE1
      dhcp_domain: blue1.local
      wan_mac: fe80::250:56ff:fe82:b21a
      lan_mac: fe80::250:56ff:fe82:62c
  vars:
    ansible_python: /usr/bin/python3
    ansible_connection: network_cli
    ansible_os: vyos
    ansible_user: vyos
