- name: install and configure wazuh agent rocky
  hosts: wazuh_agents
  become: yes

  vars:
    wazuh_manager_ip: "10.0.5.87"
    wazuh_agent_group: "linux"
    wazuh_agent_name: "{{ inventory_hostname }}"

  tasks:
    - name: dependencies
      dnf:
        name:
          - curl
          - gnupg2
        state: present

    - name: wazuh agent url download
      get_url:
        url: https://packages.wazuh.com/4.x/yum/wazuh.repo
        dest: /etc/yum.repos.d/wazuh.repo
        mode: '0644'
        headers:
          User-Agent: "Mozilla/5.0"

    - name: install wazuh agent
      dnf:
        name: wazuh-agent
        state: present

    - name: manager IP
      lineinfile:
        path: /var/ossec/etc/ossec.conf
        regexp: '<address>.*</address>'
        line: '<address>{{ wazuh_manager_ip }}</address>'

    - name: agent name
      lineinfile:
        path: /var/ossec/etc/ossec.conf
        regexp: '<name>.*</name>'
        line: '<name>{{ wazuh_agent_name }}</name>'

    - name: agent group
      lineinfile:
        path: /var/ossec/etc/ossec.conf
        regexp: '<group>.*</group>'
        line: '<group>{{ wazuh_agent_group }}</group>'

    - name: reload systemd daemon
      command: systemctl daemon-reload

    - name: enable and start wazuh
      systemd:
        name: wazuh-agent
        enabled: yes
        state: restarted
