- name: install wazuh agent and setup
  hosts: wazuh_agents
  become: yes

  vars:
    wazuh_manager_ip: "10.0.5.87"
    wazuh_agent_group: "linux"
    wazuh_agent_name: "{{ inventory_hostname }}"

  tasks:
    - name: dependencies install
      apt:
        name:
          - curl
          - apt-transport-https
          - gnupg
        state: present
        update_cache: yes

    - name: download wazuh
      get_url:
        url: https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.7.5-1_amd64.deb
        dest: /tmp/wazuh-agent.deb

    - name: install wazuh agent
      command: dpkg -i /tmp/wazuh-agent.deb

    - name: configure manager IP
      lineinfile:
        path: /var/ossec/etc/ossec.conf
        regexp: '<address>.*</address>'
        line: '<address>{{ wazuh_manager_ip }}</address>'

    - name: agent name file edit
      lineinfile:
        path: /var/ossec/etc/ossec.conf
        regexp: '<name>.*</name>'
        line: '<name>{{ wazuh_agent_name }}</name>'

    - name: agent group file edit
      lineinfile:
        path: /var/ossec/etc/ossec.conf
        regexp: '<group>.*</group>'
        line: '<group>{{ wazuh_agent_group }}</group>'

    - name: enable and start wazuh agent
      systemd:
        name: wazuh-agent
        enabled: yes
        state: restarted
