# Playbook to setup a DHCP pool on a VyOS VM
- name: vyos network configurations
  hosts: vyos
  tasks:
  - name: Version Information
    vyos_command:
      commands: show version
    register: version
    
  - debug: 
      var: version.stdout_lines

  - name: Configure DHCP Pool 
    vyos_config:
      save: yes
      lines:
      - set service dhcp-server global-parameters "local-address {{ lan_ip }}"
      - set service dhcp-server shared-network-name {{ shared_network }} authoritative
      - set service dhcp-server shared-network-name {{ shared_network }} subnet {{ lan_net }} default-router '{{ lan_ip }}'
      - set service dhcp-server shared-network-name {{ shared_network }} subnet {{ lan_net }} name-server '{{ dhcp }}'
      - set service dhcp-server shared-network-name {{ shared_network }} subnet {{ lan_net }} domain-name '{{ dhcp_domain }}'
      - set service dhcp-server shared-network-name {{ shared_network }} subnet {{ lan_net }} lease '86400'
      - set service dhcp-server shared-network-name {{ shared_network }} subnet {{ lan_net }} range {{ shared_network }}--POOL start '10.0.5.75' 
      - set service dhcp-server shared-network-name {{ shared_network }} subnet {{ lan_net }} range {{ shared_network }}--POOL stop '10.0.5.125'
